name: Supabase Keep Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:

      - name: Ping StudyAxis Project 1
        run: curl -s https://iqconwxvxqsqnxmrhhop.supabase.co/rest/v1/

      - name: Ping StudyAxis Project 2
        run: curl -s https://echltjhntwftsfmazves.supabase.co/rest/v1/

      - name: Ping StudyAxis Project 3
        run: curl -s https://xsavnjgnowobrserovrk.supabase.co/rest/v1/
